#' Regular expressions for sample identifiers
#'
#' @description
#' `regex_ids` is a centralised place for regular expressions (regex) for extracting
#' different identifiers. These expressions are then used by the
#' `extract_*` series of functions for extracting identifiers.
#'
#' Regular expressions are written as raw strings using `stringr::regex` which
#' makes them easier to understand and maintain.
#' The ["Regular Expressions" chapter in "R for Data Science"](https://r4ds.hadley.nz/regexps.html)
#' is a great resource for understanding regular expressions.
#'
#' @section DNA Database identifiers:
#'
#' **worksheet**: the worksheet identifier is "WS" followed by six numbers, which
#' increase sequentially (i.e "WS000001", "WS000002", WS000003"). Worksheets
#' are the way in which genetic tests are organised into batches within the
#' lab. Worksheet identifiers are generated by DNA Database.
#'
#' **combined_plate**: the combined plate number from the DNA Database which is
#' "CP" followed by 5 digits. "Combined plates" are created by combining
#' muliple worksheets together.
#'
#' **labno**: the numeric identifier given to every DNA sample from DNA
#' Database. The regex specifies 8 digits in the identifier, although for
#' samples from 2012 or earlier there will only be 6 digits. This identifier
#' is referred to as "labno" throughout `idtools` because this is the name
#' used in the "Samples" table of DNA Database.
#'
#' The first two digits of the labno format are the year the sample was received,
#' and then the digits increase with each new sample. For example, the first
#' sample received in 2026 would have the labno 26000001.
#'
#' **suffix**: if the same DNA sample is tested multiple times on the same
#' worksheet (which can happen
#' for repeatability experiments during test validation) then a suffix letter
#' (usually a-d) is added directly after the labno. Extracting this suffix is
#' useful when assessing the variability between different replicates of the
#' same sample.
#'
#' @section iGene identifiers:
#'
#' iGene identifiers have a consistent format of a letter signifying the
#' identifier type (R, S, D or T), followed by a consistent core identifier format.
#'
#' **igene_core**: the core iGene regex consists of the two-digit year number,
#' a hyphen, and then four alpha-numeric characters. Example: R26-AB12.
#'
#' **igene_rno**: the R (referral) number. One referral may have more than
#' one sample associated with it.
#'
#' **igene_sno**: the S (sample) number. One sample may have more than
#' one DNA extraction derived from it.
#'
#' **igene_dno**: the D (derivative) number signifies the
#' extraction-specific identifier for a sample. One derivative may have more than
#' one test associated with it.
#'
#' **igene_tno**: a T (test) number is given to a specific instance of a test
#' performed on a derivate sample.
#'
#' @section Whole genome sequencing identifiers:
#'
#' **wgs_patient_no**: the whole genome sequencing (WGS) pathway in the Genomic
#' Medicine Service uses a patient identifier which is "p" followed by 11 digits.
#'
#' **wgs_referral_no**: the referral ("r") equivalent of the WGS patient number,
#' structured as "r" followed by 11 digits.
#'
#' @returns A named list of regular expressions for different identifiers
#' @export
#'
#' @examples
#'
#' file_string <- "WS123456_12345678_sequencing_results.xlsx"
#'
#' stringr::str_extract(file_string,
#'                       pattern = regex_ids()$labno_suffix$regex,
#'                       group = regex_ids()$labno_suffix$labno_group)
#'
regex_ids <- function(){

  regex_igene_core <- paste0("\\d{2}-",         # 2 digits
                             "[[:alnum:]]{4})", # 4 alphanumeric characters
                             "(?![[:alnum:]])"  # The group must at most (?) not (!) be followed
                                                # by another alphanumeric character
                             )

  output_list <- list(

    ## DNA Database identifiers

    # Worksheet
    "worksheet" = list(
      "regex" = stringr::regex(
        r"[
        (^|\D+)             # Start of string or any non-digit character
        (WS\d{6}|ws\d{6})   # WS or ws followed by 6 digits
        (\D+|$)             # Must be followed by non-digit characters or end of string
        ]",
        comments = TRUE),
      "worksheet_group" = 2),

    # Combined plate number
    "combined_plate" = list(
      "regex" = stringr::regex(
        r"[
        (CP\d{5}|cp\d{5})    # CP or cp followed by 5 digits
        (\D+|$)              # Either a non-digit character or end of the string
        ]",
        comments = TRUE
      ),
      "combined_plate_group" = 1
    ),

    # Lab number and suffix
    "labno_suffix" = list(
      "regex" = stringr::regex(
        r"[
        (^|\D+)       # Either the start of string or non-digit characters (to
                      # prevent pulling out 8 digits from longer digit strings)
        (\d{8})       # Lab number: 8 digits
        ([a-z]{1}|)   # Suffix: either lowercase letter or empty
        (\D+|$)       # Either a non-digit character or end of the string
        ]",
        comments = TRUE),
      "labno_group" = 2,
      "suffix_group" = 3),

    # iGene identifiers

    # iGene core regex
    "igene_core" = list(
      "regex" = regex_igene_core
    ),

    # iGene R number
    "igene_rno" = list(
      "regex" = paste0("(R",
                       regex_igene_core),
      "igene_rno_group" = 1
      ),

    # iGene S number
    "igene_sno" = list(
      "regex" = paste0("(S",
                       regex_igene_core),
      "igene_sno_group" = 1
    ),

    # iGene D number
    "igene_dno" = list(
      "regex" = paste0("(D",
                       regex_igene_core),
      "igene_dno_group" = 1
    ),

    # iGene T number
    "igene_tno" = list(
      "regex" = paste0("(T",
                       regex_igene_core),
      "igene_tno_group" = 1
    ),

    ## Whole genome sequencing identifiers

    # WGS patient number
    "wgs_patient_no" = list(
      "regex" = stringr::regex(
        r"[
        (p\d{11})    # p followed by 11 digits
        (\D+|$)      # Either a non-digit character or end of the string
        ]",
        comments = TRUE
      ),
      "wgs_patient_no_group" = 1),

    # WGS referral number
    "wgs_referral_no" = list(
      "regex" = stringr::regex(
        r"[
        (r\d{11})   # r followed by 11 digits
        (\D+|$)      # Either a non-digit character or end of the string
        ]",
        comments = TRUE),
      "wgs_referral_no_group" = 1)
  )

  return(output_list)

}
